-- Usuario Administrador (email: admin@example.com, contraseña: admin)
INSERT INTO users (nombre, email, edad, fecha_nacimiento, password, role) VALUES ('Admin', 'admin@example.com', 30, '1990-01-01', '$2a$10$IX06sS9./t5sV3tA0D32FeHkCq3pgd.pI5d2d.pmRaP1oHe15M5Z6', 'ADMIN');

INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Torta Cuadrada de Chocolate', 'Deliciosa torta de chocolate con capas de ganache y un toque de avellanas. Personalizable con mensajes especiales.', 45000, 10, 'Cuadrada');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Torta Cuadrada de Frutas', 'Una mezcla de frutas frescas y crema chantilly sobre un suave bizcocho de vainilla, ideal para celebraciones.', 50000, 10, 'Cuadrada');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Torta Circular de Vainilla', 'Bizcocho de vainilla clásico relleno con crema pastelera y cubierto con un glaseado dulce, perfecto para cualquier ocasión.', 40000, 10, 'Circular');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Torta Circular de Manjar', 'Torta tradicional chilena con manjar y nueces, un deleite para los amantes de los sabores dulces y clásicos.', 42000, 10, 'Circular');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Mousse de Chocolate', 'Postre individual cremoso y suave, hecho con chocolate de alta calidad, ideal para los amantes del chocolate.', 5000, 10, 'Individual');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Tiramisú Clásico', 'Un postre italiano individual con capas de café, mascarpone y cacao, perfecto para finalizar cualquier comida.', 5500, 10, 'Individual');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Torta Sin Azúcar de Naranja', 'Torta ligera y deliciosa, endulzada naturalmente, ideal para quienes buscan opciones más saludables.', 48000, 10, 'Sin Azúcar');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Cheesecake Sin Azúcar', 'Suave y cremoso, este cheesecake es una opción perfecta para disfrutar sin culpa.', 47000, 10, 'Sin Azúcar');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Empanada de Manzana', 'Pastelería tradicional rellena de manzanas especiadas, perfecta para un dulce desayuno o merienda.', 3000, 10, 'Tradicional');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Tarta de Santiago', 'Tradicional tarta española hecha con almendras, azúcar, y huevos, una delicia para los amantes de los postres clásicos.', 6000, 10, 'Tradicional');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Brownie Sin Gluten', 'Rico y denso, este brownie es perfecto para quienes necesitan evitar el gluten sin sacrificar el sabor.', 4000, 10, 'Sin Gluten');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Pan Sin Gluten', 'Suave y esponjoso, ideal para sándwiches o para acompañar cualquier comida.', 3500, 10, 'Sin Gluten');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Torta Vegana de Chocolate', 'Torta de chocolate húmeda y deliciosa, hecha sin productos de origen animal, perfecta para veganos.', 50000, 10, 'Vegana');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Galletas Veganas de Avena', 'Crujientes y sabrosas, estas galletas son una excelente opción para un snack saludable y vegano.', 4500, 10, 'Vegana');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Torta Especial de Cumpleaños', 'Diseñada especialmente para celebraciones, personalizable con decoraciones y mensajes únicos.', 55000, 10, 'Especial');
INSERT INTO productos (nombre, descripcion, precio, stock, categoria) VALUES ('Torta Especial de Boda', 'Elegante y deliciosa, esta torta está diseñada para ser el centro de atención en cualquier boda.', 60000, 10, 'Especial');
